name: Job Dependencies

on:
  push:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Pretend to Run Tests
        run: |
          echo "Running tests..."
          echo "All tests passed!"

  build:
    needs: testing

    runs-on: ubuntu-latest

    steps:
      - name: Build Project
        run: echo "Building..."