name: Secret Practice

on:
  workflow_dispatch:
  push:

jobs:
  practice:
    runs-on: ubuntu-latest

    env:
      NAME: ${{ secrets.MY_NAME }}
      LANGUAGE: ${{ secrets.FAVORITE_LANGUAGE }}

    steps:
      - name: Display Message
        run: |
          echo "Hello $NAME!"
          echo "You love $LANGUAGE."